CREATE TABLE "Roles" (
	"IdRol"	INTEGER NOT NULL,
	"Rol"	TEXT NOT NULL,
	"EsActivo"	INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("IdRol" AUTOINCREMENT)
);

CREATE TABLE "Usuarios" (
	"IdUsuario"	INTEGER NOT NULL,
	"NombreUsuario"	TEXT NOT NULL UNIQUE,
	"CorreoElectronico"	TEXT,
	"EsActivo"	INTEGER NOT NULL DEFAULT 1,
	"IdRol"	INTEGER,
	PRIMARY KEY("IdUsuario" AUTOINCREMENT)
)